name: DEVELOPMENT - CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}

      - name: Build App
        run: |
          yarn install
          yarn vite build
      
      - name: Send Build Error Message
        if: failure()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#ff0000"
          username: "GitHub Bot"
          avatar_url: https://i.imgur.com/Kvn45ev.png
          message: Portal Aluno | Algo de errado não está certo com o código... | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  deploy: # Deploy only for DEV Env
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
    environment: development
    if: always() && !contains(needs.*.result, 'failure')

    steps:
      - name: Deploy to DEV Env
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}

      - name: Send Success Message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#00ba55"
          username: "GitHub Bot"
          avatar_url: https://i.imgur.com/Kvn45ev.png
          message: Portal Aluno | Commit '${{ github.event.head_commit.message }}' disponível no ambiente de DEV | ${{ secrets.APP_URL }}
