---
name: STAGING - CI/CD Pipeline
on:
  push:
    branches: [ staging ]
jobs:
  build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment: staging
    env:
      IMAGE_NAME: eduedu-escola-aluno-staging
      PROJECT_ID: edueduescola-teste
      REGISTRY_PREFIX: us-east1-docker.pkg.dev
      REGISTRY_NAME: eduedu-escola-aluno
      ARG_VITE_API_URL: ${{ secrets.ARG_VITE_API_URL }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIAL }}'

    - uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Build Docker Image
      run: |-
        docker build \
        --build-arg ARG_VITE_API_URL=$ARG_VITE_API_URL \
        -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker $REGISTRY_PREFIX --quiet

    - name: Push Docker Image to Artifact Registry
      run: |-
        docker tag $IMAGE_NAME:latest $REGISTRY_PREFIX/$PROJECT_ID/$REGISTRY_NAME/$IMAGE_NAME:${{github.run_number}}
        docker push $REGISTRY_PREFIX/$PROJECT_ID/$REGISTRY_NAME/$IMAGE_NAME:${{github.run_number}}

    outputs:
      git-tag: ${{ steps.increment-git-tag.outputs.git-tag }}

  deploy:
    name: Deploy New Revision
    needs: build-push
    runs-on: ubuntu-latest
    environment: STAGING
    env:
      IMAGE_NAME: eduedu-escola-aluno-staging
      PROJECT_ID: edueduescola-teste
      REGISTRY_PREFIX: us-east1-docker.pkg.dev
      REGISTRY_NAME: eduedu-escola-aluno

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIAL }}'

    - name: Deploy
      id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        service: 'eduedu-escola-aluno'
        image: '${{ env.REGISTRY_PREFIX }}/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}'
        region: us-central1

    - name: 'App URL'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
